### ISSUE TITLE
Question about line 323

### ISSUE THREAD

**Issue by donmontalvo** [dan-snelson/Setup-Your-Mac#123]
Can you remove the redundant back slash from line 323 in "Setup-Your-Mac-via-Dialog.bash"?

No impact, but it's the only one of several similar lines that has the unnecessary back slash.

I'll be in purgatory if you need me. :)

TIA

**Comment by dan-snelson** [comment]
Thanks for the feedback, @donmontalvo.

Does [Line 323](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L323) work for you sans back slashes?

**Comment by bartreardon** [comment]
the backslash is necessary though to escape the `"` characters and `${outdatedOsAction}` is contained correctly. 

`"/usr/bin/open \"${outdatedOsAction}\""`

There's four `"`'s there. two open and two closed. The inner two are appropriately escaped using `\`

Apart from that, I can't see what the issue is. Is the script not running because of these or is it a personal preference? If the latter, there's nothing stopping anyone editing their copy of the script as they see fit.

**Comment by donmontalvo** [comment]
My apologies for any confusion, the line I meant to point to contains:

**dialogApp="/Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog"**

Note the escaped space within the quoted path. It may have been fixed, since my colleague told me we are a couple versions behind. As mentioned, no impact.

**Comment by dan-snelson** [comment]
Sorry for any Dan-induced confusion, @donmontalvo.

Let first ensure we're looking at the same version:
[Setup-Your-Mac-via-Dialog.bash](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash)

**Comment by donmontalvo** [comment]
We're a couple versions behind. I must have been on an old page. The line exists in the script version we're using. The string I mentioned existed in the past. Here's a screenshot from an old post.

![DonM_ 2023-11-14 at 05 44 05](https://github.com/dan-snelson/Setup-Your-Mac/assets/20050282/0d3ecfd4-c1f6-4eb8-876c-c54f06b22dac)

**Comment by donmontalvo** [comment]
This can be closed, the new script doesn’t have it.

**Comment by bartreardon** [comment]
Ah, that makes sense then. I was confused for a bit there 🙂
