### ISSUE TITLE
When using Prompt-to-Setup-Your-Mac with Setup-Your-Mac, quitting a prompt from the former results in the "catch-all" configuration being run in the main script

### ISSUE THREAD

**Issue by justintrant** [dan-snelson/Setup-Your-Mac#83]
**Describe the bug**
When using `Prompt-to-Setup-Your-Mac` with the main `Setup-Your-Mac` script, quitting a prompt from the former results in the "catch-all" configuration being run in the main script. This results in the deployment failing.

**To Reproduce**
- Run the `Prompt-to-Setup-Your-Mac` script
- Quit one of the swiftDialog prompts using `Command+Q`
- Run the `Setup-Your-Mac` Self Service policy
- The "Catch-all" configuration should run regardless of what is configured in the main script, resulting in a failed deployment as there are no policies matching the default triggers

**Expected behavior**
Quitting the swiftDialog prompt should result in the same behavior as the user clicking 'OK', and not result in the primary script running the "Catch-all" configuration once it is run from Self Service.

**Environment**
- macOS Ventura 13.5.0
- swiftDialog 2.2.0
- Setup-Your-Mac 1.11.0

**Additional context**
https://macadmins.slack.com/archives/C04FRRN3281/p1692104941846579

**Comment by dan-snelson** [comment]
@justintrant: While [Prompt-to-Setup-Your-Mac.bash](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Prompt-to-Setup-Your-Mac.bash) has been updated, I'm confident your issue was related to other environmental variables.

Please re-re-re-test with:
- swiftDialog `2.3.1.4721`
- Prompt-to-Setup-Your-Mac.bash `0.04`
- Setup-Your-Mac-via-Dialog.bash `1.12.1`

**Comment by justintrant** [comment]
Hi @dan-snelson,

Tested and confirming that the issue is resolved. Thanks so much!

Justin.
